spring.application.name=bevflow
server.port=8080
spring.data.mongodb.uri=mongodb://mongo:27017/bevflowdb
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
management.metrics.export.datadog.api-key=<API_KEY>
management.metrics.export.datadog.step=60s
logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%p","thread":"%t","logger":"%c","message":"%m"}%n
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
